### ISSUE TITLE
Removing stats causes crashing.

### ISSUE THREAD

**Issue by MEEPofFaith** [Zelaux/AdvancedContentInfo#1]
**Describe the bug**
Removing stats causes crashing.

**To Reproduce**
1. Replace stats with astats
2. Attempt to remove `Stat.powerUse` on a block that normally does have `Stat.powerUse` (In my case, my `PayloadCrafter`s)
3. Open the stats
4. Game crash

**Expected behavior**
Just remove "Power Use: " I don't want it in my stats.

**Screenshots**
*Code without `remove` commented out.*
![code](https://user-images.githubusercontent.com/54301439/130345529-b6b0e262-496d-4928-b035-0fcf2113e5f2.png)
![error](https://user-images.githubusercontent.com/54301439/130345445-9fea20b6-4537-4961-8cc8-78c4df786d98.png)
*I just want you gone. (If I do comment out `remove`)*
![pesky power](https://user-images.githubusercontent.com/54301439/130345592-4a17bc8c-07ce-4178-9622-61739c8e8319.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version v130.0

**Additional context**
Take this experimental version of Progressed Materials, use it, and open the stats of "Missile Shell Constructer," "Missile Assembler," or "Sentry Factory" to crash the game.
[ProgMatsDesktop.zip](https://github.com/Zelaux/AdvancedContentInfo/files/7026701/ProgMatsDesktop.zip)

**Comment by Zelaux** [comment]
What is your version of the mod?
